### ISSUE TITLE
Step 3: compute optimal n sizes from both datasets

### ISSUE THREAD

**Issue by nhoizey** [cleverage/daltons#14]
- [ ] multiply both arrays to find all required image widths
- [ ] find most frequent widths (above a threshold)
- [ ] reduce the array with n pixels neighbours

**Comment by welcoMattic** [comment]
Hi @nhoizey, I'm using daltons to optimize images on the website of one of my clients, but I figure out that the step 3 is not complete. What is the actual state of daltons? Do you plan to working on the step 3 soon? I watched your talk at We Love Speed 2018, and I was impressed by the fantastic possiblities of this tool to improve images loading :slightly_smiling_face: 

Thanks!

**Comment by nhoizey** [comment]
Done in #210 🙏
