### ISSUE TITLE
Impossible to write results in file

### ISSUE THREAD

**Issue by welcoMattic** [cleverage/daltons#208]
I'm trying to write results in a file with -f option, but I catch this error 

```
Step 2: get variations of image width across viewport widths
Launch headless Chrome
Go to https://www.courbet.test
Checking widths of image main picture.c-block__img > img
Finished at viewport: 1280px
Couldn’t load page located at https://www.courbet.test:
ReferenceError: writeFile is not defined
```

Did you face this case before?

**Comment by nhoizey** [comment]
I guess the `ReferenceError: writeFile is not defined` error is a consequence of the `Couldn’t load page` issue.

Did you ever get this error with a page that could be loaded?

**Comment by welcoMattic** [comment]
Sure it was a consequence of unreachable page.
