### ISSUE TITLE
Rename to something shorter, more explicit or fun/memorable

### ISSUE THREAD

**Issue by nhoizey** [cleverage/daltons#51]
> There are only two hard things in Computer Science: cache invalidation and naming things. — [Phil Karlton](https://martinfowler.com/bliki/TwoHardThings.html)

True.

`responsive-image-widths` is not easy to spell (`image` or `images`? `width` or `widths`?) and type in a shell, so we would like to rename it to something shorter, and either more explicit or more fun/memorable.

Current options:
👍 `srcset-sizer`
😁 `daltons` (there is already [a `dalton` package on npm](https://www.npmjs.com/search?q=dalton), but there should be no ambiguity)
🎉 `BRITS`: Better Responsive Image Tools Selection
❤️ `RIWAL`: [Responsive Image Widths et AL.](https://github.com/cleverage/responsive-image-widths/issues/51#issuecomment-433333761)

You can vote with reactions, and suggest other names in comments.

**Comment by jygastaud** [comment]
BRITS (Better Responsive Image Tools Selection)

**Comment by nhoizey** [comment]
@jygastaud no mention of width or size, which is the aim of the tool?

**Comment by nhoizey** [comment]
@ryuran @vvalentin-ca do you really believe there is no risk with a catchy but non self explicit name?

**Comment by vvalentin-ca** [comment]
If the tool is interesting, it will be known by any name in my opinion.

**Comment by nhoizey** [comment]
@vvalentin-ca that's a valid point indeed.

**Comment by oliviermartinerie** [comment]
**RIWAL**
As Responsive Image Widths _et AL._ (which [means](https://fr.wiktionary.org/wiki/et_al.#Anglais) "and any other things/people/locations" from latin).
RIWAL is easy to say and to remember.
Just any idea ;)

**Comment by nhoizey** [comment]
Thanks @oliviermartinerie!

**Comment by nhoizey** [comment]
So be it, renamed to `daltons`!
