### ISSUE TITLE
Rename “contexts” to something more meaningful

### ISSUE THREAD

**Issue by nhoizey** [cleverage/daltons#53]
It should not be necessary to explain what “contexts” means, what it contains.

**Comment by ryuran** [comment]
`viewportsData` ?

**Comment by nhoizey** [comment]
Contexts contain also screen density, not only viewports.

Maybe `viewportsAndDensities`?

**Comment by ryuran** [comment]
ScreenDensity is related to viewport and not to screen because it's Also related to zoom. So, width, height and density are data about viewport.

**Comment by nhoizey** [comment]
That's right if you consider the viewport as physical pixels, but we need to consider CSS viewport and density separately.

One reason is that we might want to compress more images meant for densities above 2dppx: #64

**Comment by nhoizey** [comment]
Let's go for `stats`
