### ISSUE TITLE
Update Node.js dependency to version 10?

### ISSUE THREAD

**Issue by nhoizey** [cleverage/daltons#57]
Node.js 10 is the new LTS: 
https://medium.com/@nodejs/october-brings-node-js-10-x-to-lts-and-node-js-11-to-current-ae19f8f12b51

**Comment by ryuran** [comment]
Yes we should https://www.w3.org/2001/tag/doc/evergreen-web/

**Comment by nhoizey** [comment]
Keep v8 as minimal version while it works
